import type { TiptapNodeAttributes } from "./";
// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by: pnpm generate-render-map

/**
 * Render config for Tiptap nodes
 */
export const NODE_RENDER_MAP = {
  paragraph: {
    tag: "p",
    attrs: {},
    staticChildren: [],
  },
  doc: null,
  text: null,
  blockquote: {
    tag: "blockquote",
    attrs: {},
    staticChildren: [],
  },
  heading: {
    resolve: (attrs: TiptapNodeAttributes["heading"]) =>
      `h${attrs?.level || 1}`,
  },
  bullet_list: {
    tag: "ul",
    attrs: {},
    staticChildren: [],
  },
  ordered_list: {
    tag: "ol",
    attrs: {
      order: 1,
    },
    staticChildren: [],
  },
  list_item: {
    tag: "li",
    attrs: {},
    staticChildren: [],
  },
  code_block: {
    tag: "pre",
    attrs: {},
    staticChildren: [
      {
        tag: "code",
        attrs: {},
        staticChildren: [],
      },
    ],
  },
  hard_break: {
    tag: "br",
    attrs: {},
    staticChildren: [],
  },
  horizontal_rule: {
    tag: "hr",
    attrs: {},
    staticChildren: [],
  },
  image: {
    tag: "img",
    attrs: {},
    staticChildren: [],
  },
  emoji: {
    tag: "img",
    attrs: {
      "data-type": "emoji",
      style:
        "width: 1.25em; height: 1.25em; vertical-align: text-top; display: inline-block;",
      draggable: "false",
      loading: "lazy",
    },
    staticChildren: [],
  },
  table: {
    tag: "table",
    attrs: {
      style: "min-width: undefined",
    },
    staticChildren: [
      {
        tag: "tbody",
        attrs: {},
        staticChildren: [],
      },
    ],
  },
  tableRow: {
    tag: "tr",
    attrs: {},
    staticChildren: [],
  },
  tableCell: {
    tag: "td",
    attrs: {
      colspan: 1,
      rowspan: 1,
    },
    staticChildren: [],
  },
  tableHeader: {
    tag: "th",
    attrs: {
      colspan: 1,
      rowspan: 1,
    },
    staticChildren: [],
  },
  blok: null,
  details: {
    tag: "details",
    attrs: {},
    staticChildren: [],
  },
  detailsContent: {
    tag: "div",
    attrs: {
      "data-type": "detailsContent",
    },
    staticChildren: [],
  },
  detailsSummary: {
    tag: "summary",
    attrs: {},
    staticChildren: [],
  },
} as const;

/**
 * Render config for Tiptap marks
 */
export const MARK_RENDER_MAP = {
  link: {
    tag: "a",
    attrs: {
      target: "_blank",
      rel: "noopener noreferrer nofollow",
    },
    staticChildren: [],
  },
  textStyle: {
    tag: "span",
    attrs: {},
    staticChildren: [],
  },
  bold: {
    tag: "strong",
    attrs: {},
    staticChildren: [],
  },
  italic: {
    tag: "em",
    attrs: {},
    staticChildren: [],
  },
  strike: {
    tag: "s",
    attrs: {},
    staticChildren: [],
  },
  underline: {
    tag: "u",
    attrs: {},
    staticChildren: [],
  },
  code: {
    tag: "code",
    attrs: {},
    staticChildren: [],
  },
  superscript: {
    tag: "sup",
    attrs: {},
    staticChildren: [],
  },
  subscript: {
    tag: "sub",
    attrs: {},
    staticChildren: [],
  },
  highlight: {
    tag: "mark",
    attrs: {},
    staticChildren: [],
  },
  anchor: null,
  styled: null,
  reporter: null,
} as const;
