import type { TiptapNodeAttributes } from './index';
// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by: pnpm generate-render-map

/**
 * Render config for Tiptap nodes
 */
export const NODE_RENDER_MAP = {
  paragraph: {
  "tag": "p",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  doc: null,
  text: null,
  blockquote: {
  "tag": "blockquote",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  heading: {
    resolve: (attrs: TiptapNodeAttributes['heading']) => `h${attrs?.level || 1}`,
  },
  bullet_list: {
  "tag": "ul",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  ordered_list: {
  "tag": "ol",
  "attrs": {
    "type": null,
    "order": 1
  },
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  list_item: {
  "tag": "li",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  code_block: {
  "tag": "pre",
  "attrs": {
    "class": null
  },
  "hasHole": true,
  "children": [
    {
      "tag": "code",
      "attrs": {
        "class": null
      },
      "hasHole": true,
      "children": [
        {
          "hole": true
        }
      ]
    }
  ]
},
  hard_break: {
  "tag": "br",
  "attrs": {},
  "hasHole": false,
  "children": []
},
  horizontal_rule: {
  "tag": "hr",
  "attrs": {},
  "hasHole": false,
  "children": []
},
  image: {
  "tag": "img",
  "attrs": {
    "src": null,
    "alt": null,
    "title": null,
    "width": null,
    "height": null,
    "id": null,
    "source": null,
    "copyright": null,
    "meta_data": null
  },
  "hasHole": false,
  "children": []
},
  emoji: {
  "tag": "span",
  "attrs": {
    "data-type": "emoji",
    "data-name": null,
    "data-emoji": null
  },
  "hasHole": false,
  "children": [
    {
      "tag": "img",
      "attrs": {
        "src": null,
        "style": "width: 1.25em; height: 1.25em; vertical-align: text-top; display: inline-block;",
        "draggable": "false",
        "loading": "lazy"
      },
      "hasHole": false,
      "children": []
    }
  ]
},
  table: {
  "tag": "table",
  "attrs": {
    "style": "min-width: undefined"
  },
  "hasHole": true,
  "children": [
    {
      "tag": "tbody",
      "attrs": {},
      "hasHole": true,
      "children": [
        {
          "hole": true
        }
      ]
    }
  ]
},
  tableRow: {
  "tag": "tr",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  tableCell: {
  "tag": "td",
  "attrs": {
    "colspan": 1,
    "rowspan": 1,
    "colwidth": null,
    "backgroundColor": null
  },
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  tableHeader: {
  "tag": "th",
  "attrs": {
    "colspan": 1,
    "rowspan": 1,
    "colwidth": null
  },
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  blok: null,
  details: {
  "tag": "details",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  detailsContent: {
  "tag": "div",
  "attrs": {
    "data-type": "detailsContent"
  },
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  detailsSummary: {
  "tag": "summary",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
} as const;

/**
 * Render config for Tiptap marks
 */
export const MARK_RENDER_MAP = {
  link: {
  "tag": "a",
  "attrs": {
    "target": "_blank",
    "rel": "noopener noreferrer nofollow",
    "class": null,
    "href": null,
    "title": null,
    "linktype": null
  },
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  textStyle: {
  "tag": "span",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  bold: {
  "tag": "strong",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  italic: {
  "tag": "em",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  strike: {
  "tag": "s",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  underline: {
  "tag": "u",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  code: {
  "tag": "code",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  superscript: {
  "tag": "sup",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  subscript: {
  "tag": "sub",
  "attrs": {},
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  highlight: {
  "tag": "mark",
  "attrs": {
    "color": null
  },
  "hasHole": true,
  "children": [
    {
      "hole": true
    }
  ]
},
  anchor: null,
  styled: null,
  reporter: null,
} as const;

export type NodeRenderMap = typeof NODE_RENDER_MAP;
export type MarkRenderMap = typeof MARK_RENDER_MAP;
export type MarkType = keyof typeof MARK_RENDER_MAP;
export type NodeType = keyof typeof NODE_RENDER_MAP;
