// scripts/generate-richtext-types.ts
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getSchema } from '@tiptap/core';
import { defaultExtensions } from '../src/lib/richtext-renderer/extentions';
import type { Schema, NodeType, MarkType } from 'prosemirror-model';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Converts a schema attrs object to a TS property string (with type from hints)
 * E.g. { color: { default: null } } -> 'color?: string | null;'
 */
function getAttrType(attrName: string, _def: any): string {
  // Could extend for more attributes if needed
  const hints: Record<string, string> = {
    level: '1 | 2 | 3 | 4 | 5 | 6',
    textAlign: "'left' | 'center' | 'right' | 'justify' | null",
    color: 'string | null',
    class: 'string | null',
    id: 'string | null',
    href: 'string',
    linktype: "'url' | 'story' | 'asset' | 'email'",
    src: 'string',
    alt: 'string',
    title: 'string | null',
    width: 'number | string | null',
    height: 'number | string | null',
    rel: 'string | null',
    target: "'_self' | '_blank' | '_parent' | '_top' | null",
    order: 'number',
    colspan: 'number', rowspan: 'number', colwidth: 'number[] | null',
    backgroundColor: 'string | null',
    body: 'SbBlokData[]',
    emoji: 'string | null',
    name: 'string | null',
    fallbackImage: 'string | null',
    reporter: 'never',
    // Expand as needed
  };
  return hints[attrName] || 'any';
}

function genAttrsType(attrs: Record<string, any> | undefined): string {
  if (!attrs || Object.keys(attrs).length === 0) return 'Record<string, never>';
  let out = '{ ';
  for (const [attrName, attrVal] of Object.entries(attrs)) {
    const typeStr = getAttrType(attrName, attrVal);
    out += `${attrName}?: ${typeStr}; `;
  }
  out += '}';
  return out;
}

/** Generate all node attribute interfaces and helpers */
function genAttributeTypes(schema: Schema) {
  let nodeAttrs = '';
  let markAttrs = '';

  for (const [name, type] of Object.entries(schema.nodes) as [string, NodeType][]) {
    nodeAttrs += `  ${name}: ${genAttrsType(type.spec.attrs)};\n`;
  }

  for (const [name, type] of Object.entries(schema.marks) as [string, MarkType][]) {
    markAttrs += `  ${name}: ${genAttrsType(type.spec.attrs)};\n`;
  }

  return { nodeAttrs, markAttrs };
}

/** Generate PMNode discriminated union type */
function genPMNode(schema: Schema): string {
  let out = 'export type PMNode =\n';

  for (const [name, type] of Object.entries(schema.nodes) as [string, NodeType][]) {
    const hasText = name === 'text' ? 'text: string;' : '';

    let children = '';
    if (type.isBlock || name === 'doc' || type.spec.content || type.isInline) {
      children = 'content?: PMNode[];';
    }

    out += `  | { type: '${name}'; attrs?: TiptapNodeAttributes['${name}']; ${children} marks?: PMMark[]; ${hasText} }\n`;
  }

  return out + ';';
}

function genPMMark(schema: Schema): string {
  let out = 'export type PMMark =\n';
  for (const [name, type] of Object.entries(schema.marks)) {
    out += `  | { type: '${name}'; attrs?: TiptapMarkAttributes['${name}']; }\n`;
  }
  return out + ';';
}

function main() {
  const extensions = Object.values(defaultExtensions);
  const schema = getSchema(extensions as any);

  let output = '';
  output += '// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.\n';
  output += '// Generated by: pnpm generate-richtext-types\n\n';
  output += `import type { SbBlokData } from './types';\n\n`;

  // --- Attribute types
  output += '/** Attribute types for all Tiptap node extensions */\n';
  output += 'export interface TiptapNodeAttributes {\n';
  output += genAttributeTypes(schema).nodeAttrs;
  output += '}\n\n';
  output += '/** Attribute types for all Tiptap mark extensions */\n';
  output += 'export interface TiptapMarkAttributes {\n';
  output += genAttributeTypes(schema).markAttrs;
  output += '}\n\n';

  // --- Node name unions
  output += 'export type TiptapNodeName = keyof TiptapNodeAttributes;\n';
  output += 'export type TiptapMarkName = keyof TiptapMarkAttributes;\n';
  output += 'export type TiptapComponentName = TiptapNodeName | TiptapMarkName;\n\n';

  // --- PMNode/PMMark
  output += genPMNode(schema) + '\n\n';
  output += genPMMark(schema) + '\n\n';

  // --- Core root type
  output += '/** Canonical type for a Storyblok RichText JSON root */\n';
  output += 'export type StoryblokRichTextJson = PMNode;\n\n';

  // --- Component prop typing
  output += '/** Typed override map for node/mark components */\n';
  output += 'export interface RichTextComponentProps<T extends TiptapComponentName> {\n';
  output += '  attrs: T extends TiptapNodeName\n    ? TiptapNodeAttributes[T]\n    : T extends TiptapMarkName ? TiptapMarkAttributes[T] : never;\n';
  output += '  node?: T extends TiptapNodeName ? PMNode : undefined;\n';
  output += '  mark?: T extends TiptapMarkName ? PMMark : undefined;\n';
  output += '}\n\n';
  output += 'export type StoryblokRichTextComponentMap = {\n';
  output += '  [K in TiptapComponentName]?: (props: RichTextComponentProps<K>) => any;\n';
  output += '};\n\n';

  const outPath = path.join(__dirname, '../src/lib/richtext-renderer/richtext-types.generated.ts');
  fs.writeFileSync(outPath, output, 'utf-8');
  console.log('Generated: ', outPath);
}

main();
